### ISSUE TITLE
Error running mvn clean install - missing dependencies

### ISSUE THREAD

**Issue by cphelm** [SAP/cloud-marketing-campaign-insights#1]
When running mvn clean install with in the services directory I am getting the following error: 
[ERROR] Failed to execute goal on project marketing-insight-application: Could not resolve dependencies for project com.sap.cec.mkt:marketing-insight-application:war:1.0.0: Could not find artifact org.apache.olingo:olingo-odata2-core:jar:2.0.8-sap-08 in central (https://repo.maven.apache.org/maven2)

Any idea how to resolve?
cheers!

**Comment by rabish108** [comment]
Hi,

Please try with version 2.0.8 instead of 2.0.8-sap-08.

Thanks!
